Timeslot  and timezone
naklar-io/naklar.io pull request #194
Opened 2021-04-12 14:06 UTC by nylser

Working on adjusting calculation to make sure a time slot doesn't drift over DST changes

2021-09-13 16:40 UTC, nylser commented
@juli303 Review here!

2021-09-14 10:40 UTC, Techthy requested changes

2021-09-14 10:40 UTC, Techthy commented on frontend/naklario/src/app/user-list/user-list.component.scss
> +@import '~bootstrap/scss/functions';
pls remove

2021-09-14 10:40 UTC, Techthy commented on frontend/naklario/src/app/user-list/user-list.component.html
> +<div class="container" *ngIf="constants$ | async as constants">
pls remove file

2021-09-14 10:40 UTC, Techthy commented on frontend/naklario/src/app/user-list/user-list.component.ts
> +import { HttpParams } from '@angular/common/http';
pls remove file

2021-09-14 10:40 UTC, Techthy commented on frontend/naklario/src/app/user-list/user-list.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
pls remove file

2021-09-14 10:42 UTC, juli303 requested changes
Ich würd's gerne noch auf Herz und Nieren prüfen, bitte noch nicht mergen

2021-09-14 10:42 UTC, nylser commented
> Ich würd's gerne noch auf Herz und Nieren prüfen, bitte noch nicht mergen

ja, wenn möglich bitte noch vor Ende der Woche

2021-09-20 08:33 UTC, juli303 approved these changes

2021-09-20 10:49 UTC, Techthy approved these changes

2021-09-20 10:49 UTC, merged