[NAK-299] configuration options
naklar-io/naklar.io pull request #195
Opened 2021-04-13 17:33 UTC by nylser

2021-04-15 07:36 UTC, juli303 requested changes
Nach dem löschen aller Custom-Links ist trotzdem nicht die Standardleiste sichtbar

2021-04-20 11:32 UTC, nylser commented
> Nach dem löschen aller Custom-Links ist trotzdem nicht die Standardleiste sichtbar

Das war eigentlich fast so beabsichtigt, da man ja vielleicht auch gar keine Links da anzeigen möchte. Man kann ja die Custom-navbar auch ausschalten

2021-04-23 18:42 UTC, nylser commented
@juli303 bräuchten das bald, kannst du nochmal schauen?

2021-04-23 18:48 UTC, juli303 commented
beim deployen gabs nen fehler

2021-04-23 18:56 UTC, nylser commented
> beim deployen gabs nen fehler

reran

2021-04-23 18:59 UTC, juli303 commented
wenn die custom navbar inaktiv ist, sind trotzdem nicht die normalen links sichtbar

2021-04-23 19:16 UTC, juli303 approved these changes

2021-04-23 19:16 UTC, merged