[NAK-820] cancel appointment reason
naklar-io/naklar.io pull request #276
Opened 2021-10-26 11:01 UTC by Techthy

Backend is missing

2021-11-19 08:21 UTC, nylser commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/cancel-appointment-modal/cancel-appointment-modal.component.html
> +                    Wir versuchen eine:n andere:n Tutor:in für den:die Schüler:in zu finden.
Gibt es einen Grund dafür, dass wir dem Tutor nicht die genaue Info geben ob der Termin weitergeleitet wird? Wir haben ja die Info

2021-11-21 20:42 UTC, Techthy commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/cancel-appointment-modal/cancel-appointment-modal.component.html
> +                    Wir versuchen eine:n andere:n Tutor:in für den:die Schüler:in zu finden.
Ne gibt es nicht. Was würdest du denn vorschlagen, dass da steht, wenn wir keine Alternative haben?

2021-11-22 08:14 UTC, nylser requested changes

2021-11-22 08:14 UTC, nylser commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/appointment-card.component.ts
> +        const pronoun =
maybe refactor pronoun into a global util? (Also Angular Pipes might be elegant here)

2021-11-22 08:14 UTC, nylser commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/cancel-appointment-modal/cancel-appointment-modal.component.html
> +                    Wir versuchen eine:n andere:n Tutor:in für den:die Schüler:in zu finden.
Wenn es die Alternative gibt: Die Terminanfrage wird an einen anderen Tutor weitergeleitet.
Wenn nicht: Leider konnten wir keinen anderen Tutor für diesen Termin finden.

Nur mein Vorschlag: Würde das auch allgemein bei nicht direkten Terminen anzeigen. Das macht das System noch etwas transparenter. Finde es jetzt sowieso schon besser wenn wir dem Tutor mitteilen, dass wir weiterleiten.

2021-11-22 08:14 UTC, nylser commented on frontend/naklario/src/app/services/database/scheduling/appointment.service.ts
> +    hasAlternatives(id: number): Observable<AppointmentAlternative> {
the API-Endpoint is called has_alternative so please name the method equally: `hasAlternative()`

2021-11-22 08:14 UTC, nylser commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/appointment-card.component.html
> +                            [title]="getDirectTitle(appointment, currentUser)"
Those abbr seem to be displayed on mobile, but you can't interact with them. In the future we might need a solution which also works there.

2021-11-22 14:41 UTC, Techthy commented on frontend/naklario/src/app/scheduling/components/appointment/appointment-card/cancel-appointment-modal/cancel-appointment-modal.component.html
> +                    Wir versuchen eine:n andere:n Tutor:in für den:die Schüler:in zu finden.
Leider können wir diesen Termin nicht an einen Tutor weiterleiten.

2021-11-23 09:14 UTC, nylser approved these changes

2021-11-23 09:16 UTC, nylser commented
Build is still failing after merge. Migrations need to be merged: `./manage.py makemigrations --merge`

2021-11-23 09:29 UTC, nylser approved these changes

2021-11-23 09:33 UTC, merged