Nak 815/feedback after session
naklar-io/naklar.io pull request #323
Opened 2021-12-12 21:28 UTC by Techthy

2021-12-13 16:06 UTC, nylser requested changes

2021-12-13 16:06 UTC, nylser commented on frontend/naklario/src/app/roulette/components/feedback/feedback.component.html
> +                        users.receiver.firstName +
Suggestion:
'Dieses Feedback wird VORNAME später angezeigt. Verhalte dich bitte respektvoll :)'
More correct german maybe ;)

2021-12-13 17:25 UTC, Techthy commented on frontend/naklario/src/app/static/pages/privacy/privacy.component.html
>  </ion-header>
Hier habe ich keine Changes gemacht. @juli303 du hast irgendwie auf dieser Branch zwei Commits.
Kann das hier weg? Eigentlich müsste das doch in der Branch von NAK- 677 sein

2021-12-14 09:06 UTC, nylser approved these changes

2021-12-14 11:53 UTC, merged